- name: backend
  hosts: backend
  become: yes
  tasks:
    - name: Disable Node.js module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable Node.js 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: latest
    
    - name: Add expense user
      ansible.builtin.user:
        name: expense