- name: configure backend server
  hosts: backend
  become: yes
  tasks:
    - name: Disable Node.js module
      ansible.builtin.command: dnf module disable nodejs -y

    - name: Enable Node.js 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed
    
    - name: Add expense user
      ansible.builtin.user:
        name: expense
    
    - name: Download backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /app