- name: db
  hosts: db
  become: yes
  vars:
    login_host: db.byklabs.store
  vars_prompt:
  - name: mysql_root_password
    prompt: enter root password
    private: no  
  tasks:
  - name: Install MySQL server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: Install MySQL dependencies
    ansible.builtin.pip:
     name: 
     - PyMySQL
     - cryptography
     state: latest
     
    
  - name: check DB connection
    community.mysql.mysql_info:
     login_user: root
     login_password: ExpenseApp@1
     login_host: "{{login_host}}"
     filter: version
    ignore_errors: yes 
    register: mysql_connection_info
  
  - name: print connection output
    ansible.builtin.debug:
      msg: "{{mysql_connection_info}}"

  - name: setup root login_password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"
    when: mysql_connection_info.failed = True